### PR TITLE
Tarea Individual-5: Introducir "sample data" del rol "Manager" y entidades "Project" y "UserStory" | guigomrom

### PR DESCRIPTION
**Pull request by guillegomezz8**

### CODE REVIEW

**Review by angelneria — CHANGES_REQUESTED** [review]
You have to create sample data for entities project and user story too

**Review by ManuelVelezLopez — APPROVED** [review]
Ok!

**Review by josbaqrod — APPROVED** [review]
This looks great

**Review by PedroPabloSantos — APPROVED** [review]
Everythinh is okay

**Review by angelneria — APPROVED** [review]
It´s okay

**Pull request merged**
